-- FDA food-recall findings (display-only; never feeds scoring — invariant #4).
-- Auto-generated by scripts/fetch-recalls.mjs from the openFDA API.
-- Idempotent: re-paste anytime; the NOT EXISTS guard skips existing rows.
-- Paste AFTER the schema/commodity migrations.

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-22', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1339-2026%22', '[Class I] Sprouts may be contaminated with STEC E. coli and/or Salmonella.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1339-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1379-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1379-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1355-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'onion'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1355-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1355-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1355-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-19', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1342-2026%22', '[Class II] Product may be contaminated with Salmonella'
from commodities c where c.slug = 'mango'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1342-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1356-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'onion'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1356-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1356-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1356-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1376-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1376-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1376-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'mushroom'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1376-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1377-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1377-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1372-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1372-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1374-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1374-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1374-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'mango'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1374-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1366-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'onion'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1366-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1366-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1366-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-22', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1338-2026%22', '[Class I] Sprouts may be contaminated with STEC E. coli and/or Salmonella.'
from commodities c where c.slug = 'onion'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1338-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1375-2026%22', '[Class I] Jalapenos have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1375-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-07', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1344-2026%22', '[Class I] Potential contamination with Salmonella.'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1344-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'E. coli', c.id, '2026-08-28', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1380-2026%22', '[Class I] Potential E. coli O145:H28 Contamination'
from commodities c where c.slug = 'strawberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1380-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'E. coli', c.id, '2026-08-28', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1380-2026%22', '[Class I] Potential E. coli O145:H28 Contamination'
from commodities c where c.slug = 'blueberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1380-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'E. coli', c.id, '2026-08-28', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1380-2026%22', '[Class I] Potential E. coli O145:H28 Contamination'
from commodities c where c.slug = 'blackberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1380-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-06', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1302-2026%22', '[Class I] Products were manufactured with jalapenos that have the potential to be contaminated with Salmonella'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1302-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1262-2026%22', '[Class I] Potential Salmonella Javiana contamination'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1262-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'E. coli', c.id, '2026-06-25', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1238-2026%22', '[Class I] Due to potential E. coli O145:H28 contamination'
from commodities c where c.slug = 'blueberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1238-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1256-2026%22', '[Class I] Jalapenos may be contaminated with Salmonella.'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1256-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'E. coli', c.id, '2026-06-25', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1239-2026%22', '[Class I] Due to potential E. coli O145:H28 contamination'
from commodities c where c.slug = 'blueberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1239-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-08-05', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1257-2026%22', '[Class I] Potential Salmonella contamination'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1257-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-07-22', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1242-2026%22', '[Class I] Potential Salmonella Javiana contamination'
from commodities c where c.slug = 'bell_pepper'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1242-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1293-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1293-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1293-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1293-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1293-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1293-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1286-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1286-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1297-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1283-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1283-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1299-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1289-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1289-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1289-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1289-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1282-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1282-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1291-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1291-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1291-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1291-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1292-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1292-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1292-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1292-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1292-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1292-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1281-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1281-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1285-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1285-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1288-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1288-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1288-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1288-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1287-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1287-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1280-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1280-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1296-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1296-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1296-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1296-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1296-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1296-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1279-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1279-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1294-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1294-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1294-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1294-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1294-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1294-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1298-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1284-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1284-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1290-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'romaine'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1290-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1290-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1290-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1295-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'lettuce'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1295-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1295-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'carrot'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1295-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Cyclospora', c.id, '2026-07-17', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1295-2026%22', '[Class I] Potential Cyclospora contamination.'
from commodities c where c.slug = 'cabbage'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1295-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'E. coli', c.id, '2026-07-03', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1181-2026%22', '[Class I] Potential E. coli O145:H28 Contamination'
from commodities c where c.slug = 'blueberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1181-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-05-18', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1078-2026%22', '[Class II] Potential for Salmonella'
from commodities c where c.slug = 'strawberry'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-1078-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Listeria monocytogenes', c.id, '2026-05-11', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0939-2026%22', '[Class I] Imported Enoki Mushrooms tested positive for Listeria Monocytogenes.'
from commodities c where c.slug = 'mushroom'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0939-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-05-01', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0887-2026%22', '[Class I] Products may be potentially contaminated with Salmonella.'
from commodities c where c.slug = 'onion'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0887-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Salmonella', c.id, '2026-05-01', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0886-2026%22', '[Class I] Products may be potentially contaminated with Salmonella.'
from commodities c where c.slug = 'onion'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0886-2026%22' and f.commodity_id = c.id);

insert into contamination_findings (kind, analyte, commodity_id, reported_on, source_name, source_url, summary)
select 'pathogen', 'Listeria monocytogenes', c.id, '2026-05-14', 'FDA', 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0898-2026%22', '[Class I] Imported Enoki Mushrooms samples collected by Florida Department of Health tested positive for Listeria Monocytogenes.'
from commodities c where c.slug = 'mushroom'
and not exists (select 1 from contamination_findings f
  where f.source_url = 'https://api.fda.gov/food/enforcement.json?search=recall_number:%22H-0898-2026%22' and f.commodity_id = c.id);
