// Turn a REVIEWED proposed-products CSV into an insert migration you paste in
// the Supabase SQL Editor. This is the second half of the M9 human-in-the-loop
// flow: ingest -> hand-review the CSV (delete junk, fix commodity/origin) ->
// this -> paste.
//
//   node scripts/csv-to-sql.mjs [--in path/to.csv]
//
// Resolves commodity/origin by slug/country_code at insert time and de-dupes on
// GTIN (ON CONFLICT DO NOTHING), so it never clobbers curated rows and is safe
// to re-run.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const COMMODITY_SLUGS = new Set([
  "spinach", "kale", "carrot", "sweet_potato", "potato", "strawberry",
  "blueberry", "green_bean", "bell_pepper", "peach", "pea", "broccoli",
  "winter_squash", "banana",
]);
const FORMS = new Set(["fresh", "frozen", "canned", "dried", "juice"]);
const COUNTRY_CODES = new Set(["US", "MX", "CA", "PE", "CL", "CN", "TR", "IN"]);

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

function latestCsv() {
  const dir = new URL("./out/", import.meta.url);
  const files = readdirSync(dir)
    .filter((f) => f.startsWith("proposed_products_") && f.endsWith(".csv"))
    .sort();
  if (!files.length) throw new Error("no proposed_products_*.csv in scripts/out/");
  return new URL(files[files.length - 1], dir);
}

function parseCsv(text) {
  const rows = [];
  for (const line of text.trim().split("\n")) {
    const cells = [];
    let cur = "";
    let q = false;
    for (const c of line) {
      if (c === '"') q = !q;
      else if (c === "," && !q) {
        cells.push(cur);
        cur = "";
      } else cur += c;
    }
    cells.push(cur);
    rows.push(cells);
  }
  const header = rows.shift();
  return rows.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""])));
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

function slugifyBrand(name) {
  return name
    .split(",")[0]
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function main() {
  const inUrl = arg("in") ? new URL(arg("in"), `file://${process.cwd()}/`) : latestCsv();
  const rows = parseCsv(readFileSync(inUrl, "utf8"));

  const brands = new Map(); // slug -> display_name
  const products = [];
  const skipped = [];

  for (const r of rows) {
    const gtin = (r.gtin || "").trim();
    const name = (r.display_name || "").trim();
    const slug = (r.commodity_slug || "").trim();
    if (!/^[0-9]{14}$/.test(gtin) || !name || !COMMODITY_SLUGS.has(slug)) {
      skipped.push(`${gtin || "?"} ${name || "?"} (bad gtin/name/commodity)`);
      continue;
    }
    const form = FORMS.has(r.form) ? r.form : "fresh";
    const organic = String(r.is_organic).toLowerCase() === "true";
    const cc = (r.origin_country_code || "").trim().toUpperCase();
    const originOk = cc && COUNTRY_CODES.has(cc);
    if (cc && !originOk) {
      skipped.push(`${gtin} ${name} (unknown origin ${cc})`);
      continue;
    }

    let brandSlug = null;
    if (r.brand && r.brand.trim()) {
      brandSlug = slugifyBrand(r.brand.trim());
      if (brandSlug && !brands.has(brandSlug)) {
        brands.set(brandSlug, r.brand.split(",")[0].trim());
      }
    }

    products.push({
      gtin, name, brandSlug, slug, form, organic,
      cc: originOk ? cc : null,
      confidence: originOk ? "documented" : "inferred",
    });
  }

  const lines = [];
  lines.push("-- Generated by scripts/csv-to-sql.mjs from a reviewed OFF ingest.");
  lines.push("-- Paste into Supabase SQL Editor. Safe to re-run (ON CONFLICT DO NOTHING).");
  lines.push("");

  if (brands.size) {
    lines.push("-- Brands");
    for (const [bslug, bname] of brands) {
      lines.push(
        `insert into brands (slug, display_name) values (${q(bslug)}, ${q(bname)}) on conflict (slug) do nothing;`,
      );
    }
    lines.push("");
  }

  lines.push("-- Products");
  for (const p of products) {
    const brandExpr = p.brandSlug
      ? `(select id from brands where slug = ${q(p.brandSlug)})`
      : "null";
    const originExpr = p.cc
      ? `(select id from origins where country_code = ${q(p.cc)} and region is null)`
      : "null";
    lines.push(
      `insert into products (gtin, display_name, brand_id, commodity_id, form, is_organic, origin_id, origin_confidence, data_source)\n` +
        `select ${q(p.gtin)}, ${q(p.name)}, ${brandExpr}, ` +
        `(select id from commodities where slug = ${q(p.slug)}), ` +
        `${q(p.form)}, ${p.organic}, ${originExpr}, ${q(p.confidence)}, 'open_food_facts'\n` +
        `on conflict (gtin) do nothing;`,
    );
  }

  const stamp = new Date().toISOString().slice(0, 10);
  const outUrl = new URL(`./out/import_${stamp}.sql`, import.meta.url);
  writeFileSync(outUrl, lines.join("\n") + "\n");

  console.log(`read:     ${inUrl.pathname.replace(/%20/g, " ")}`);
  console.log(`products: ${products.length}`);
  console.log(`brands:   ${brands.size}`);
  console.log(`skipped:  ${skipped.length}`);
  skipped.slice(0, 10).forEach((s) => console.log(`  - ${s}`));
  console.log(`wrote:    ${outUrl.pathname.replace(/%20/g, " ")}`);
}

main();
